### ISSUE TITLE
Fix issue on https://www.1337lawyers.com/causes/justice-for-rickie-slaughter/

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/web#28]
This image should be served with gatsby-image, not a static file, and should have a max-width of 1024px in the desktop setting and horizontally centered.

**Comment by KostyaZgara** [comment]
I have implemented this task, but I don't have permission to push my branch and then create a PR. Please give me access and make "master" branch protected for security purpose.

**Comment by shicholas** [comment]
thank you! closing this.
