### ISSUE TITLE
Proposition for how to resolve issues

### ISSUE THREAD

**Issue by KostyaZgara** [1337lawyers/web#32]
For tracking resolving issues, I'd like to suggest pattern for naming branches like "issue-idIssue".
For example, You've created issue https://github.com/1337lawyers/web/issues/28 his number is 28. I can create a branch with the name "issue-28" and push to the repo. Then create a merge request.

In this way, we can easily track changes and if something will go wrong after accomplishing some of the tasks, we can make rollout.

In this case, I need to have write access to the repo and you should set "master" branch as protected.

**Comment by shicholas** [comment]
This is fine, I don't think this matters so long as the PR is attached to the issue. GitHub has a very basic Kanban board, which I think should suffice.

I don't know why I need to give you write access to the master branch, as the deploys of this repo are set up with CI/CD directly to CircleCI => AWS and I would like to review all of your work in PR form.

**Comment by KostyaZgara** [comment]
We don't need access to "master" branch. I'd like to suggest make "master" branch as protected and with full access only for you and restricted for me so that I can push my "issues-" branches.

**Comment by shicholas** [comment]
This is resolved now with merged PRs
