### ISSUE TITLE
Proposition about code formatting

### ISSUE THREAD

**Issue by KostyaZgara** [1337lawyers/web#33]
I have some suggestions to edit eslint configuration:

1. Allow default exports
When use default exports, we can develop a convenience structure where one file is one component and don't need to use a curly brace in import.

2. Allow tabs indent.
It's just our wish. I'm used to using tab, as for me much easier press tab than several times space

3. Allow extra semicolon
It's a good code style that has come from times C/C++/Java. In this way, we can easy to see where the statement ends and where there was just a line break

**Comment by shicholas** [comment]
I enjoy coding with named exports because I've worked with teams that have confused default exports. IMO it reduces the chance of error. Page components in Gatsby are an exception since they require a default export.

The other two changes I am fine with if you want to change the `.eslint` file, run `yarn lint --fix` and PR.

**Comment by KostyaZgara** [comment]
Sorry, but I see everywhere the parts of code like that https://prnt.sc/p6sqzj So I can guess in this project developers often use default exports and brings unnecessary lines of code for disabling eslint rules.

But we can work and with named exports, it's just our observation. Our suggestion is only to follow a single code style either named exports and fix files with default export or use default exports and to fix files with named exports

**Comment by shicholas** [comment]
@KostyaZgara can I close this?

**Comment by KostyaZgara** [comment]
@shicholas If you approved all of my changes from my PR #39 then yes, you can close this issue as well

**Comment by shicholas** [comment]
cool
